name: "Linkcheck and buildtest on PR"

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: "setup python"
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: "install dependencies"
      run: |
        apt-get update -y && apt-get install -y git
        pip install -r requirements.txt
    - uses: ammaraskar/sphinx-problem-matcher@master
    - name: "check links"
      run: |
        source bin/setup_env.sh
        make linkcheck
    - name: "Test doc building"
      run: |
        source bin/setup_env.sh
        make html
